//actions
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const WATCHLIST_LOAD = 'WATCHLIST_LOAD';
export const WATCHLIST_LOAD_SUCCESS = 'WATCHLIST_LOAD_SUCCESS';
export const WATCHLIST_ACTION_PENDING = 'WATCHLIST_ACTION_PENDING';
export const WATCHLIST_ADD_ITEM_COMPLETE = 'WATCHLIST_ADD_ITEM_COMPLETE';
export const WATCHLIST_DELETE_ITEM_COMPLETE = 'WATCHLIST_DELETE_ITEM_COMPLETE';

export const SEARCH_MEDIA = 'SEARCH_MEDIA';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';

export const USER_LOGIN_REQUEST_TOKEN = 'USER_LOGIN_REQUEST_TOKEN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ACCESS_TOKEN_CREATED = 'USER_LOGIN_ACCESS_TOKEN_CREATED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CREATE_SESSION = 'USER_CREATE_SESSION';